apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-name
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mypvc
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    storageClassName: storage-class-name
# SC provision persistent volumes dynamicaly in the backgrourd , enable storage to scale up for deployemnt 
# Stoarge backed is defined in the SC component 
#- via provisioner attribute, each stoage backend has own provisioner
# - internal provisioner - ' kunernertes.io'
# external provision